spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/infotree_db
    username: rms
    password: rms123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc.lob.non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: trbtree

server:
  port: 8081
jwt:
  secret: ${JWT_SECRET}
  access-expiration: 900000   # 15 min
  refresh-expiration: 604800000 # 7 days
springdoc:
  override-with-generic-response: false
logging:
  level:
    org.springframework: INFO
    org.springframework.security: DEBUG
    com.tr.rms: DEBUG
spring.jackson:
  serialization:
    WRITE_DATES_AS_TIMESTAMPS: false
